POST http://localhost:8001/products
Content-Type: application/json

{"name":  "Pepsi", "price": 5.0, "quantity":  10}

###

POST http://localhost:8001/products
Content-Type: application/json

{"name":  "Kawa", "price": 8.0, "quantity":  9}

###

GET http://localhost:8001/products
Accept: application/json

###

POST http://localhost:8001/orders
Accept: application/json

###

GET http://localhost:8001/orders
Accept: application/json

###

POST http://localhost:8001/cards
Content-Type: application/json

{"orderId":  "07994e40-e89e-47bc-bdae-400aaba149ed", "productName": "Kawa"}

###

POST http://localhost:8001/cards
Content-Type: application/json

{"orderId":  "07994e40-e89e-47bc-bdae-400aaba149ed", "productName": "Pepsi"}

###

POST http://localhost:8000/payments
Content-Type: application/json

{"orderId":  "07994e40-e89e-47bc-bdae-400aaba149ed", "amount": 12.0}

###

POST http://localhost:8000/payments
Content-Type: application/json

{"orderId":  "07994e40-e89e-47bc-bdae-400aaba149ed", "amount": 1.0}

###
